
global.rpg = {
  emoticon(string) {
    string = string.toLowerCase()
    let emot = {
      role: '🚗',
      level: '⚡'
    }
    let results = Object.keys(emot).map(v => [v, new RegExp(v, 'gi')]).filter(v => v[1].test(string))
    if (!results.length) return ''
    else return emot[results[0][0]]
  },[
  { name: 'Rookie', level: 0 },
  { name: 'Amateur', level: 4 },
  { name: 'Intermediate', level: 8 },
  { name: 'Pro', level: 12 },
  { name: 'Expert', level: 16 },
  { name: 'Veteran', level: 20 },
  { name: 'Master', level: 24 },
  { name: 'Champion', level: 28 },
  { name: 'Grandmaster', level: 32 },
  { name: 'Legend', level: 36 },
  { name: 'Racing Legend', level: 40 },
  { name: 'Speed Demon', level: 44 },
  { name: 'Track King', level: 48 },
  { name: 'Race Ace', level: 52 },
  { name: 'Speedster', level: 56 },
  { name: 'Racing Prodigy', level: 60 },
  { name: 'Supreme Racer', level: 64 },
  { name: 'Ultimate Driver', level: 68 },
  { name: 'Racing Maestro', level: 72 },
  { name: 'Speed Guru', level: 76 },
  { name: 'Racing Phenom', level: 80 },
  { name: 'Speed Titan', level: 84 },
  { name: 'Track Legend', level: 88 },
  { name: 'Race Wizard', level: 92 },
  { name: 'Velocity Master', level: 96 },
  { name: 'Racing Virtuoso', level: 100 },
  { name: 'Speed Savant', level: 104 },
  { name: 'Track Emperor', level: 108 },
  { name: 'Race Magician', level: 112 },
  { name: 'Speed Sorcerer', level: 116 },
  { name: 'Racing Legend', level: 120 },
  { name: 'Speed Demon', level: 124 },
  { name: 'Track King', level: 128 },
  { name: 'Race Ace', level: 132 },
  { name: 'Speedster', level: 136 },
  { name: 'Racing Prodigy', level: 140 },
  { name: 'Supreme Racer', level: 144 },
  { name: 'Ultimate Driver', level: 148 },
  { name: 'Racing Maestro', level: 152 },
  { name: 'Speed Guru', level: 156 },
  { name: 'Racing Phenom', level: 160 },
  { name: 'Speed Titan', level: 164 },
  { name: 'Track Legend', level: 168 },
  { name: 'Race Wizard', level: 172 },
  { name: 'Velocity Master', level: 176 },
  { name: 'Racing Virtuoso', level: 180 },
  { name: 'Speed Savant', level: 184 },
  { name: 'Track Emperor', level: 188 },
  { name: 'Race Magician', level: 192 },
  { name: 'Speed Sorcerer', level: 196 },
  { name: 'Racing Legend', level: 200 },
  { name: 'Speed Demon', level: 204 },
  { name: 'Track King', level: 208 },
  { name: 'Race Ace', level: 212 },
  { name: 'Speedster', level: 216 },
  { name: 'Racing Prodigy', level: 220 },
  { name: 'Supreme Racer', level: 224 },
  { name: 'Ultimate Driver', level: 228 },
  { name: 'Racing Maestro', level: 232 },
  { name: 'Speed Guru', level: 236 },
  { name: 'Racing Phenom', level: 240 },
  { name: 'Speed Titan', level: 244 },
  { name: 'Track Legend', level: 248 },
  { name: 'Race Wizard', level: 252 },
  { name: 'Velocity Master', level: 256 },
  { name: 'Racing Virtuoso', level: 260 },
  { name: 'Speed Savant', level: 264 },
  { name: 'Track Emperor', level: 268 },
  { name: 'Race Magician', level: 272 },
  { name: 'Speed Sorcerer', level: 276 },
  { name: 'Racing Legend', level: 280 },
  { name: 'Speed Demon', level: 284 },
  { name: 'Track King', level: 288 },
  { name: 'Race Ace', level: 292 },
  { name: 'Speedster', level: 296 },
  { name: 'Racing Prodigy', level: 300 },
  { name: 'Supreme Racer', level: 304 },
  { name: 'Ultimate Driver', level: 308 },
  { name: 'Racing Maestro', level: 312 },
  { name: 'Speed Guru', level: 316 },
  { name: 'Racing Phenom', level: 320 },
  { name: 'Speed Titan', level: 324 },
  { name: 'Track Legend', level: 328 },
  { name: 'Race Wizard', level: 332 },
  { name: 'Velocity Master', level: 336 },
  { name: 'Racing Virtuoso', level: 340 },
  { name: 'Speed Savant', level: 344 },
  { name: 'Track Emperor', level: 348 },
  { name: 'Race Magician', level: 352 },
  { name: 'Speed Sorcerer', level: 356 },
  { name: 'Racing Legend', level: 360 },
  { name: 'Speed Demon', level: 364 },
  { name: 'Track King', level: 368 },
  { name: 'Race Ace', level: 372 },
  { name: 'Speedster', level: 376 },
  { name: 'Racing Prodigy', level: 380 },
  { name: 'Supreme Racer', level: 384 },
  { name: 'Ultimate Driver', level: 388 },
  { name: 'Racing Maestro', level: 392 },
  { name: 'Speed Guru', level: 396 },
  { name: 'Racing Phenom', level: 400 },
  { name: 'Speed Titan', level: 404 },
  { name: 'Track Legend', level: 408 },
  { name: 'Race Wizard', level: 412 },
  { name: 'Velocity Master', level: 416 },
  { name: 'Racing Virtuoso', level: 420 },
  { name: 'Speed Savant', level: 424 },
  { name: 'Track Emperor', level: 428 },
  { name: 'Race Magician', level: 432 },
  { name: 'Speed Sorcerer', level: 436 },
  { name: 'Racing Legend', level: 440 },
  { name: 'Speed Demon', level: 444 },
  { name: 'Track King', level: 448 },
  { name: 'Race Ace', level: 452 },
  { name: 'Speedster', level: 456 },
  { name: 'Racing Prodigy', level: 460 },
  { name: 'Supreme Racer', level: 464 },
  { name: 'Ultimate Driver', level: 468 },
  { name: 'Racing Maestro', level: 472 },
  { name: 'Speed Guru', level: 476 },
  { name: 'Racing Phenom', level: 480 },
  { name: 'Speed Titan', level: 484 },
  { name: 'Track Legend', level: 488 },
  { name: 'Race Wizard', level: 492 },
  { name: 'Velocity Master', level: 496 },
  { name: 'Racing Virtuoso', level: 500 },
  { name: 'Speed Savant', level: 504 },
  { name: 'Track Emperor', level: 508 },
  { name: 'Race Magician', level: 512 },
  { name: 'Speed Sorcerer', level: 516 },
  { name: 'Racing Legend', level: 520 },
  { name: 'Speed Demon', level: 524 },
  { name: 'Track King', level: 528 },
  { name: 'Race Ace', level: 532 },
  { name: 'Speedster', level: 536 },
  { name: 'Racing Prodigy', level: 540 },
  { name: 'Supreme Racer', level: 544 },
  { name: 'Ultimate Driver', level: 548 },
  { name: 'Racing Maestro', level: 552 },
  { name: 'Speed Guru', level: 556 },
  { name: 'Racing Phenom', level: 560 },
  { name: 'Speed Titan', level: 564 },
  { name: 'Track Legend', level: 568 },
  { name: 'Race Wizard', level: 572 },
  { name: 'Velocity Master', level: 576 },
  { name: 'Racing Virtuoso', level: 580 },
  { name: 'Speed Savant', level: 584 },
  { name: 'Track Emperor', level: 588 },
  { name: 'Race Magician', level: 592 },
  { name: 'Speed Sorcerer', level: 596 },
  { name: 'Racing Legend', level: 600 },
  { name: 'Speed Demon', level: 604 },
  { name: 'Track King', level: 608 },
  { name: 'Race Ace', level: 612 },
  { name: 'Speedster', level: 616 },
  { name: 'Racing Prodigy', level: 620 },
  { name: 'Supreme Racer', level: 624 },
  { name: 'Ultimate Driver', level: 628 },
  { name: 'Racing Maestro', level: 632 },
  { name: 'Speed Guru', level: 636 },
  { name: 'Racing Phenom', level: 640 },
  { name: 'Speed Titan', level: 644 },
  { name: 'Track Legend', level: 648 },
  { name: 'Race Wizard', level: 652 },
  { name: 'Velocity Master', level: 656 },
  { name: 'Racing Virtuoso', level: 660 },
  { name: 'Speed Savant', level: 664 },
  { name: 'Track Emperor', level: 668 },
  { name: 'Race Magician', level: 672 },
  { name: 'Speed Sorcerer', level: 676 },
  { name: 'Racing Legend', level: 680 },
  { name: 'Speed Demon', level: 684 },
  { name: 'Track King', level: 688 },
  { name: 'Race Ace', level: 692 },
  { name: 'Speedster', level: 696 },
  { name: 'Racing Prodigy', level: 700 },
  { name: 'Supreme Racer', level: 704 },
  { name: 'Ultimate Driver', level: 708 },
  { name: 'Racing Maestro', level: 712 },
  { name: 'Speed Guru', level: 716 },
  { name: 'Racing Phenom', level: 720 },
  { name: 'Speed Titan', level: 724 },
  { name: 'Track Legend', level: 728 },
  { name: 'Race Wizard', level: 732 },
  { name: 'Velocity Master', level: 736 },
  { name: 'Racing Virtuoso', level: 740 },
  { name: 'Speed Savant', level: 744 },
  { name: 'Track Emperor', level: 748 },
  { name: 'Race Magician', level: 752 },
  { name: 'Speed Sorcerer', level: 756 },
  { name: 'Racing Legend', level: 760 },
  { name: 'Speed Demon', level: 764 },
  { name: 'Track King', level: 768 },
  { name: 'Race Ace', level: 772 },
  { name: 'Speedster', level: 776 },
  { name: 'Racing Prodigy', level: 780 },
  { name: 'Supreme Racer', level: 784 },
  { name: 'Ultimate Driver', level: 788 },
  { name: 'Racing Maestro', level: 792 },
  { name: 'Speed Guru', level: 796 },
  { name: 'Racing Phenom', level: 800 },
  { name: 'Speed Titan', level: 804 },
  { name: 'Track Legend', level: 808 },
  { name: 'Race Wizard', level: 812 },
  { name: 'Velocity Master', level: 816 },
  { name: 'Racing Virtuoso', level: 820 },
  { name: 'Speed Savant', level: 824 },
  { name: 'Track Emperor', level: 828 },
  { name: 'Race Magician', level: 832 },
  { name: 'Speed Sorcerer', level: 836 },
  { name: 'Racing Legend', level: 840 },
  { name: 'Speed Demon', level: 844 },
  { name: 'Track King', level: 848 },
  { name: 'Race Ace', level: 852 },
  { name: 'Speedster', level: 856 },
  { name: 'Racing Prodigy', level: 860 },
  { name: 'Supreme Racer', level: 864 },
  { name: 'Ultimate Driver', level: 868 },
  { name: 'Racing Maestro', level: 872 },
  { name: 'Speed Guru', level: 876 },
  { name: 'Racing Phenom', level: 880 },
  { name: 'Speed Titan', level: 884 },
  { name: 'Track Legend', level: 888 },
  { name: 'Race Wizard', level: 892 },
  { name: 'Velocity Master', level: 896 },
  { name: 'Racing Virtuoso', level: 900 },
  { name: 'Speed Savant', level: 904 },
  { name: 'Track Emperor', level: 908 },
  { name: 'Race Magician', level: 912 },
  { name: 'Speed Sorcerer', level: 916 },
  { name: 'Racing Legend', level: 920 },
  { name: 'Speed Demon', level: 924 },
  { name: 'Track King', level: 928 },
  { name: 'Race Ace', level: 932 },
  { name: 'Speedster', level: 936 },
  { name: 'Racing Prodigy', level: 940 },
  { name: 'Supreme Racer', level: 944 },
  { name: 'Ultimate Driver', level: 948 },
  { name: 'Racing Maestro', level: 952 },
  { name: 'Speed Guru', level: 956 },
  { name: 'Racing Phenom', level: 960 },
  { name: 'Speed Titan', level: 964 },
  { name: 'Track Legend', level: 968 },
  { name: 'Race Wizard', level: 972 },
  { name: 'Velocity Master', level: 976 },
  { name: 'Racing Virtuoso', level: 980 },
  { name: 'Speed Savant', level: 984 },
  { name: 'Track Emperor', level: 988 },
  { name: 'Race Magician', level: 992 },
  { name: 'Speed Sorcerer', level: 996 },
  { name: 'Racing Legend', level: 1000 }
]
   

    return role.reverse().find(role => level >= role.level)
  }
}
